### PR TITLE
Add store enumeration [session storage]

### PR DESCRIPTION
**Pull request by jan-johansson-mr**
Hi,

Here is a draft for the enumeration of keys. Please review and if you think it's fine, then I'll go ahead and add to local storage. And then fix the documentation. The solution is upgraded to latest Blazor version.

Thanks,
//Jan

### CODE REVIEW

**Comment by jan-johansson-mr** [comment]
Hi, upon reviewing storage behavior, I realized that we can simplify enumeration of keys slightly.

**Comment by jan-johansson-mr** [comment]
Hi,

Please review and give feedback

Thanks,
@chrissainty, @titanix

**Comment by chrissainty** [comment]
@jan-johansson-mr I've had a scan through the changes on GitHub and everything looks good. I'll pull down the branch at some point today/tomorrow and run it all just to double-check but I think we're looking good.

**Comment by jan-johansson-mr** [comment]
Thanks,
I've updated the readme file.

**Comment by jan-johansson-mr** [comment]
Hi @chrissainty,

A friendly reminder :-)

**Comment by chrissainty** [comment]
Yes, sorry I will get to this, I just have some personal stuff I need to deal with. Should get to it over the weekend.

**Comment by jan-johansson-mr** [comment]
Hi there @chrissainty,

I've introduced feature of enumerate items (race condition aware), please have a look.

Thanks

**Comment by jan-johansson-mr** [comment]
Hi @chrissainty,
I've updated session storage too, to be the same as local storage, so all changes here also applies to local storage.
Thanks

**Pull request closed without merging**
